[build]
rustflags = ["-Ctarget-cpu=native", "-Cpanic=abort"]
target = "./x86_64-unknown-none-rusty_mikan.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]